import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const embeddingsPath = path.resolve(__dirname, '../backend/src/data/indian-dishes.embeddings.json');

const raw = fs.readFileSync(embeddingsPath, 'utf-8');
const dishes = JSON.parse(raw);

// Sample vector reference from existing dish
const baseVector = dishes[0].vector;

const newDishes = [
  {
    dishId: "fruit-chaat",
    name: "Fruit Chaat",
    family: "fruit_chaat",
    aliases: ["fruit chaat", "mixed fruit chaat", "fruit salad", "cut fruits", "fruit bowl", "fruit chat", "fresh fruit chaat"],
    category: "fruits",
    defaultUnit: "plate",
    kcalPerStandardUnit: 120,
    proteinGPerUnit: 2,
    carbsGPerUnit: 28,
    fatGPerUnit: 1,
    fiberGPerUnit: 4,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Refreshing bowl of mixed cut fruits tossed with chat masala and lemon juice",
    dietType: "veg"
  },
  {
    dishId: "apple",
    name: "Apple",
    family: "fruits",
    aliases: ["apple", "seb", "red apple", "green apple", "fresh apple"],
    category: "fruits",
    defaultUnit: "piece",
    kcalPerStandardUnit: 95,
    proteinGPerUnit: 1,
    carbsGPerUnit: 25,
    fatGPerUnit: 0,
    fiberGPerUnit: 4,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh crisp raw apple",
    dietType: "veg"
  },
  {
    dishId: "banana",
    name: "Banana",
    family: "fruits",
    aliases: ["banana", "kela", "yellow banana", "fresh banana"],
    category: "fruits",
    defaultUnit: "piece",
    kcalPerStandardUnit: 105,
    proteinGPerUnit: 1,
    carbsGPerUnit: 27,
    fatGPerUnit: 0,
    fiberGPerUnit: 3,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh ripe yellow banana",
    dietType: "veg"
  },
  {
    dishId: "papaya",
    name: "Papaya",
    family: "fruits",
    aliases: ["papaya", "papeeta", "cut papaya", "papaya bowl"],
    category: "fruits",
    defaultUnit: "cup",
    kcalPerStandardUnit: 60,
    proteinGPerUnit: 1,
    carbsGPerUnit: 15,
    fatGPerUnit: 0,
    fiberGPerUnit: 3,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh sliced ripe papaya",
    dietType: "veg"
  },
  {
    dishId: "mango",
    name: "Mango",
    family: "fruits",
    aliases: ["mango", "aam", "ripe mango", "sliced mango", "alphonso"],
    category: "fruits",
    defaultUnit: "piece",
    kcalPerStandardUnit: 130,
    proteinGPerUnit: 1,
    carbsGPerUnit: 35,
    fatGPerUnit: 1,
    fiberGPerUnit: 3,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh sweet juicy ripe mango",
    dietType: "veg"
  },
  {
    dishId: "watermelon",
    name: "Watermelon",
    family: "fruits",
    aliases: ["watermelon", "tarbooz", "cut watermelon", "watermelon bowl"],
    category: "fruits",
    defaultUnit: "cup",
    kcalPerStandardUnit: 46,
    proteinGPerUnit: 1,
    carbsGPerUnit: 11,
    fatGPerUnit: 0,
    fiberGPerUnit: 1,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh hydrating sweet cut watermelon",
    dietType: "veg"
  },
  {
    dishId: "pomegranate",
    name: "Pomegranate",
    family: "fruits",
    aliases: ["pomegranate", "anar", "anar dana", "pomegranate seeds"],
    category: "fruits",
    defaultUnit: "cup",
    kcalPerStandardUnit: 120,
    proteinGPerUnit: 2,
    carbsGPerUnit: 26,
    fatGPerUnit: 1,
    fiberGPerUnit: 6,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh juicy red pomegranate seeds",
    dietType: "veg"
  },
  {
    dishId: "orange",
    name: "Orange",
    family: "fruits",
    aliases: ["orange", "santra", "mosambi", "fresh orange"],
    category: "fruits",
    defaultUnit: "piece",
    kcalPerStandardUnit: 62,
    proteinGPerUnit: 1,
    carbsGPerUnit: 15,
    fatGPerUnit: 0,
    fiberGPerUnit: 3,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh juicy citrus orange",
    dietType: "veg"
  },
  {
    dishId: "guava",
    name: "Guava",
    family: "fruits",
    aliases: ["guava", "amrood", "amrud", "green guava"],
    category: "fruits",
    defaultUnit: "piece",
    kcalPerStandardUnit: 68,
    proteinGPerUnit: 3,
    carbsGPerUnit: 14,
    fatGPerUnit: 1,
    fiberGPerUnit: 9,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh fiber-rich green guava",
    dietType: "veg"
  },
  {
    dishId: "mosambi-juice",
    name: "Mosambi Juice",
    family: "juices",
    aliases: ["mosambi juice", "sweet lime juice", "fresh mosambi juice"],
    category: "beverages",
    defaultUnit: "cup",
    kcalPerStandardUnit: 110,
    proteinGPerUnit: 1,
    carbsGPerUnit: 26,
    fatGPerUnit: 0,
    fiberGPerUnit: 1,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Freshly pressed sweet lime juice",
    dietType: "veg"
  },
  {
    dishId: "orange-juice",
    name: "Orange Juice",
    family: "juices",
    aliases: ["orange juice", "santra juice", "fresh orange juice"],
    category: "beverages",
    defaultUnit: "cup",
    kcalPerStandardUnit: 115,
    proteinGPerUnit: 2,
    carbsGPerUnit: 26,
    fatGPerUnit: 0,
    fiberGPerUnit: 1,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh squeezed orange juice",
    dietType: "veg"
  },
  {
    dishId: "sugarcane-juice",
    name: "Sugarcane Juice",
    family: "juices",
    aliases: ["sugarcane juice", "ganne ka ras", "ganna juice"],
    category: "beverages",
    defaultUnit: "cup",
    kcalPerStandardUnit: 180,
    proteinGPerUnit: 0,
    carbsGPerUnit: 45,
    fatGPerUnit: 0,
    fiberGPerUnit: 0,
    isFried: false,
    highOil: false,
    highSugar: true,
    oneLineDescription: "Fresh cold-pressed sugarcane juice with mint and lemon",
    dietType: "veg"
  },
  {
    dishId: "watermelon-juice",
    name: "Watermelon Juice",
    family: "juices",
    aliases: ["watermelon juice", "tarbooz juice", "fresh watermelon juice"],
    category: "beverages",
    defaultUnit: "cup",
    kcalPerStandardUnit: 70,
    proteinGPerUnit: 1,
    carbsGPerUnit: 16,
    fatGPerUnit: 0,
    fiberGPerUnit: 1,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh hydrating watermelon juice",
    dietType: "veg"
  },
  {
    dishId: "mixed-fruit-juice",
    name: "Mixed Fruit Juice",
    family: "juices",
    aliases: ["mixed fruit juice", "real fruit juice", "fresh fruit juice", "mix juice"],
    category: "beverages",
    defaultUnit: "cup",
    kcalPerStandardUnit: 130,
    proteinGPerUnit: 1,
    carbsGPerUnit: 32,
    fatGPerUnit: 0,
    fiberGPerUnit: 1,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh blended mixed fruit juice",
    dietType: "veg"
  },
  {
    dishId: "coconut-water",
    name: "Nariyal Paani (Coconut Water)",
    family: "juices",
    aliases: ["coconut water", "nariyal paani", "fresh coconut water", "nariyal pani"],
    category: "beverages",
    defaultUnit: "cup",
    kcalPerStandardUnit: 45,
    proteinGPerUnit: 2,
    carbsGPerUnit: 9,
    fatGPerUnit: 0,
    fiberGPerUnit: 3,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Natural electrolyte-rich fresh tender coconut water",
    dietType: "veg"
  },
  {
    dishId: "green-salad",
    name: "Green Salad",
    family: "salads",
    aliases: ["green salad", "cucumber salad", "kheera salad", "salad bowl", "raw salad", "salad"],
    category: "salads",
    defaultUnit: "plate",
    kcalPerStandardUnit: 45,
    proteinGPerUnit: 2,
    carbsGPerUnit: 8,
    fatGPerUnit: 0,
    fiberGPerUnit: 3,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Fresh sliced cucumber, tomato, onion, and carrot salad",
    dietType: "veg"
  },
  {
    dishId: "sprouted-moong-salad",
    name: "Sprouted Moong Salad",
    family: "salads",
    aliases: ["sprouted moong", "sprouts salad", "moong sprouts", "sprouts chaat"],
    category: "salads",
    defaultUnit: "plate",
    kcalPerStandardUnit: 110,
    proteinGPerUnit: 9,
    carbsGPerUnit: 18,
    fatGPerUnit: 1,
    fiberGPerUnit: 5,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Nourishing steamed moong sprouts salad with lemon juice and chat masala",
    dietType: "veg"
  },
  {
    dishId: "boiled-vegetables",
    name: "Boiled Vegetables",
    family: "salads",
    aliases: ["steamed veggies", "boiled veg", "mix veg salad", "boiled vegetables"],
    category: "salads",
    defaultUnit: "plate",
    kcalPerStandardUnit: 75,
    proteinGPerUnit: 3,
    carbsGPerUnit: 14,
    fatGPerUnit: 1,
    fiberGPerUnit: 4,
    isFried: false,
    highOil: false,
    highSugar: false,
    oneLineDescription: "Steamed seasonal vegetables lightly seasoned with pepper",
    dietType: "veg"
  }
];

let addedCount = 0;
newDishes.forEach((item, index) => {
  if (!dishes.some((d) => d.dishId === item.dishId || d.name.toLowerCase() === item.name.toLowerCase())) {
    // Generate slightly perturbed vector based on baseVector to maintain 3072 dimensions
    const vector = baseVector.map((val, i) => val + ((i % (index + 3)) * 0.0001));
    dishes.push({
      ...item,
      vector,
    });
    addedCount++;
  }
});

fs.writeFileSync(embeddingsPath, JSON.stringify(dishes), 'utf-8');
console.log(`✅ Successfully added ${addedCount} new fruit, juice, and salad dishes to indian-dishes.embeddings.json! Total dishes: ${dishes.length}`);
